# Generated by Django 6.0.1 on 2026-04-03 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0034_shopstatus_shoptype_skilltype_remove_event_event_and_more'),
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='selected_character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.character'),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
