# Generated by Django 3.1.5 on 2021-01-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20210112_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='warriortypeparametersleveltemplate',
            name='value',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
