# Generated by Django 3.1.5 on 2021-01-13 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20210113_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='warriorleveltemplate',
            name='newwarrior_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='new', to='game.warriortype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warriorleveltemplate',
            name='warrior_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='old', to='game.warriortype'),
        ),
    ]
