# Generated by Django 3.1.5 on 2021-01-13 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_auto_20210113_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warriorleveltemplate',
            name='warrior_type',
        ),
    ]
