# Generated by Django 3.1.5 on 2021-01-13 22:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_auto_20210113_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warriorleveltemplate',
            name='warrior_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.warriortype'),
        ),
    ]
