# Generated by Django 3.1.5 on 2021-01-14 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_auto_20210114_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characterparameter',
            name='player',
        ),
        migrations.AddField(
            model_name='characterparameter',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='game.character'),
            preserve_default=False,
        ),
    ]
