# Generated by Django 3.1.5 on 2021-01-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_warriorleveltemplate_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=20)),
                ('weeks', models.PositiveIntegerField()),
                ('rolls', models.PositiveIntegerField()),
            ],
        ),
    ]
