# Generated by Django 3.1.5 on 2021-01-16 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_auto_20210116_2053'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name': 'party', 'verbose_name_plural': 'parties'},
        ),
    ]
