# Generated by Django 3.1.5 on 2021-01-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0026_auto_20210117_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='party_leader',
            field=models.BooleanField(default=False),
        ),
    ]
