# Generated by Django 3.1.5 on 2021-01-17 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0028_auto_20210117_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='name',
        ),
    ]
