# Generated by Django 3.1.5 on 2021-01-17 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0029_remove_party_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='party',
        ),
        migrations.AddField(
            model_name='character',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='game.character'),
            preserve_default=False,
        ),
    ]
