# Generated by Django 3.1.5 on 2021-01-25 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0032_auto_20210125_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('done', models.BooleanField(default=False)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.character')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.eventtable')),
            ],
        ),
        migrations.DeleteModel(
            name='CharacterEvent',
        ),
    ]
