# Generated by Django 3.1.5 on 2021-01-13 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20210113_2215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WarriorTemplate',
            new_name='WarriorLevelTemplate',
        ),
        migrations.DeleteModel(
            name='oldLevelTemplate',
        ),
    ]
