# Generated by Django 3.1.5 on 2021-01-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_auto_20210113_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='attacks',
            new_name='oldattacks',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='initiative',
            new_name='oldinitiative',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='luck',
            new_name='oldluck',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='pinning',
            new_name='oldpinning',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='skills',
            new_name='oldskills',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='willpower',
            new_name='oldwillpower',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='wounds',
            new_name='wounds_dice',
        ),
        migrations.AddField(
            model_name='warriorleveltemplate',
            name='newpinning',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
