# Generated by Django 3.1.5 on 2021-01-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20210113_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='oldluck',
            new_name='attacks',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='oldattacks',
            new_name='initiative',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='oldwillpower',
            new_name='luck',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='newpinning',
            new_name='pinning',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='oldpinning',
            new_name='skills',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='oldskills',
            new_name='willpower',
        ),
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='oldinitiative',
            new_name='wounds_modifier',
        ),
    ]
