# Generated by Django 3.1.5 on 2021-01-13 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_warriorleveltemplate_warrior_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warriorleveltemplate',
            old_name='newwarrior_type',
            new_name='warrior_type',
        ),
    ]
