# Generated by Django 3.1.5 on 2021-01-13 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20210113_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='characterparameter',
            name='desc',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
