# Generated by Django 3.1.5 on 2021-01-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_auto_20210114_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='warriorleveltemplate',
            name='move',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
