# Generated by Django 3.1.5 on 2021-01-16 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_journey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
