# Generated by Django 3.1.5 on 2021-01-16 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0024_auto_20210116_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.party'),
        ),
    ]
