# Generated by Django 3.1.5 on 2021-01-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0025_auto_20210116_2324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='characterparameter',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='equipment',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='gold',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='parameter',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='warriortype',
            old_name='desc',
            new_name='description',
        ),
    ]
