# Generated by Django 3.1.5 on 2021-01-17 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0027_character_party_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='party_leader',
        ),
        migrations.AddField(
            model_name='party',
            name='leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='game.character'),
            preserve_default=False,
        ),
    ]
