# Generated by Django 3.1.5 on 2021-01-17 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0030_auto_20210117_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='leader_set', to='game.character'),
        ),
    ]
