# Generated by Django 6.0.1 on 2026-04-03 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0033_auto_20210125_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ShopType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('availability', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
        migrations.AddField(
            model_name='character',
            name='active_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='character',
            name='ticks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='after_form',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='before_form',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='command',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='leader_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.event'),
        ),
        migrations.AddField(
            model_name='item',
            name='buy_price',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='item',
            name='chance_to_be_in_shop',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='command',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='item',
            name='restriction',
            field=models.ManyToManyField(to='game.warriortype'),
        ),
        migrations.AddField(
            model_name='item',
            name='sell_price',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skill',
            name='restriction',
            field=models.ManyToManyField(to='game.warriortype'),
        ),
        migrations.AddField(
            model_name='warriortype',
            name='alehouse_roll',
            field=models.CharField(default='2D6', max_length=10),
        ),
        migrations.AlterField(
            model_name='character',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='characterparameter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='eventtype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='gold',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='journeytable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='parameter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='race',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='warriorleveltemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='warriortype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CharacterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.character')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.skill')),
            ],
        ),
        migrations.CreateModel(
            name='EventTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=100)),
                ('before_form', models.TextField(blank=True)),
                ('after_form', models.TextField(blank=True)),
                ('description_copy', models.TextField(blank=True)),
                ('command', models.TextField(default='{}')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.eventtype')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='game.eventtemplate'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('next_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.location')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.RESTRICT, to='game.location'),
        ),
        migrations.CreateModel(
            name='LocationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('character_position', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('weeks_of_journey_to', models.PositiveIntegerField(default=0)),
                ('is_settlement', models.BooleanField(default=False)),
                ('is_journey', models.BooleanField(default=False)),
                ('next_location_desc', models.CharField(max_length=100)),
                ('next_location_url', models.CharField(max_length=100)),
                ('no_of_dices', models.PositiveIntegerField(default=0)),
                ('living_expenses', models.PositiveIntegerField(default=1)),
                ('name_of_period', models.CharField(default='day', max_length=4)),
                ('next_location', models.ManyToManyField(to='game.locationtemplate')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.locationtemplate'),
        ),
        migrations.AddField(
            model_name='journeytable',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.locationtemplate'),
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('forbidden', models.ManyToManyField(to='game.warriortype')),
                ('shop_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.shoptype')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='available_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.shop'),
        ),
        migrations.CreateModel(
            name='SettlementActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField(default=1)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.character')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.location')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.shop')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.shopstatus')),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='game.skilltype'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='EventTable',
        ),
    ]
