# Generated by Django 4.2.27 on 2026-04-05 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0036_item_initial_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='description',
        ),
        migrations.RemoveField(
            model_name='adventure',
            name='name',
        ),
        migrations.AddField(
            model_name='adventure',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.adventuretemplate'),
        ),
        migrations.AddField(
            model_name='adventuretemplate',
            name='objective_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.objectiveroom'),
        ),
    ]
