# Generated by Django 4.2.27 on 2026-04-05 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0037_objectiveroom_remove_adventure_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpellType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='available_in',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.shop'),
        ),
        migrations.AddField(
            model_name='spell',
            name='spell_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='game.spelltype'),
        ),
    ]
