# Generated by Django 4.2.27 on 2026-04-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0038_spelltype_alter_item_available_in_spell_spell_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='spell',
            name='characters',
            field=models.ManyToManyField(blank=True, related_name='known_spells', through='game.CharacterSpell', to='game.character'),
        ),
    ]
