# Generated by Django 4.2.27 on 2026-04-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0039_spell_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_armour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_shield',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_weapon',
            field=models.BooleanField(default=False),
        ),
    ]
