# Generated by Django 4.2.27 on 2026-04-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0040_equipment_is_active_item_is_armour_item_is_shield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warriortype',
            name='can_cast_spells',
            field=models.BooleanField(default=False),
        ),
    ]
