# Generated by Django 4.2.27 on 2026-04-06 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0041_warriortype_can_cast_spells'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SkillType',
            new_name='Durability',
        ),
        migrations.AddField(
            model_name='item',
            name='durability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.durability'),
        ),
    ]
