# Generated by Django 4.2.27 on 2026-04-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0042_rename_skilltype_durability_item_durability'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_ballistic_weapon',
            field=models.BooleanField(default=False),
        ),
    ]
