# Generated by Django 4.2.27 on 2026-04-06 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0043_item_is_ballistic_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_armour_for', to='game.equipment'),
        ),
        migrations.AddField(
            model_name='character',
            name='ballistic_weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_ballistic_weapon_for', to='game.equipment'),
        ),
        migrations.AddField(
            model_name='character',
            name='boots',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_boots_for', to='game.equipment'),
        ),
        migrations.AddField(
            model_name='character',
            name='helmet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_helmet_for', to='game.equipment'),
        ),
        migrations.AddField(
            model_name='character',
            name='shield',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_shield_for', to='game.equipment'),
        ),
        migrations.AddField(
            model_name='character',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_weapon_for', to='game.equipment'),
        ),
        migrations.AddField(
            model_name='item',
            name='is_boots',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='is_helmet',
            field=models.BooleanField(default=False),
        ),
    ]
