# Generated by Django 4.2.27 on 2026-07-30 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0046_set_helmet_item_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='power_reroll_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='power_reroll_turns', to='game.character'),
        ),
        migrations.AddField(
            model_name='turn',
            name='power_reroll_pending',
            field=models.BooleanField(default=False),
        ),
    ]
