# Generated by Django 4.2.27 on 2026-07-31 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0050_spiked_pit_roll_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('weapon_skill', models.PositiveIntegerField(help_text='WS')),
                ('ballistic_skill', models.PositiveIntegerField(blank=True, help_text='BS target number (e.g. 5 means 5+); blank if no ranged attack', null=True)),
                ('strength', models.PositiveIntegerField(help_text='S')),
                ('toughness', models.PositiveIntegerField(help_text='T')),
                ('wounds', models.PositiveIntegerField(help_text='W')),
                ('attacks', models.PositiveIntegerField(help_text='A')),
                ('move', models.PositiveIntegerField(help_text='Move')),
                ('gold_value', models.PositiveIntegerField(default=0)),
                ('battle_level', models.PositiveIntegerField(default=1, help_text='Difficulty / Battle Level used when scaling encounters')),
                ('special_rules', models.TextField(blank=True, help_text='Free-text or JSON-encoded special rules from the monster card')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='card_kind',
            field=models.CharField(blank=True, choices=[('M', 'Monster'), ('E', 'Special')], db_index=True, help_text='M = Monster encounter, E = Special event (blank for non-deck events)', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='draw_another_event',
            field=models.BooleanField(default=False, help_text='After resolving, draw another Unexpected Event'),
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='draw_treasure',
            field=models.BooleanField(default=False, help_text='After resolving (typically after combat), draw a Treasure card'),
        ),
        migrations.CreateModel(
            name='EventTemplateMonster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default='1', help_text='Fixed count or dice expression, e.g. "1D6", "1D3+1", "6"', max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('event_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monster_entries', to='game.eventtemplate')),
                ('monster', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='event_entries', to='game.monster')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'unique_together': {('event_template', 'monster')},
            },
        ),
        migrations.AddField(
            model_name='eventtemplate',
            name='monsters',
            field=models.ManyToManyField(blank=True, related_name='event_templates', through='game.EventTemplateMonster', to='game.monster'),
        ),
    ]
